server:
  port: 8081
  servlet:
    session:
      timeout: 3000s
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    # 使用druid数据源
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      validationQuery: select 'x' from dual
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,slf4j
  cloud:
    loadbalancer:
      retry:
        enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
  ##上传文件的大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mapper/mybatis-config.xml
#mybatis分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.neusoft.bootstore.*.mapper: debug
    com.neusoft.bootstore: debug
  config: classpath:logback-spring.xml
##fdfs
fdfs:
  tracker-list: 49.234.6.119:22122
  hostPort: http://litongxin.cn/